version: '2'
services:
  ramiel.discord:
    environment:
      DiscordToken: ""
      GuildId: ""
      LavalinkHostname: "lavalink"
      LavalinkPort: "2333"
      LavalinkPassword: "youshallnotpass"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - lavalink

  lavalink:
    image: fredboat/lavalink:master-vv3.3.2.5
    volumes:
      - ./config/lavalink.yml:/opt/Lavalink/application.yml
  