version: '2'
services:
  ramiel.discord:
    environment:
      DISCORD_TOKEN: ""
      DISCORD_GUILD_ID: ""
      DISCORD_REMOVE_COMMANDS: "false"
      LAVALINK_ENDPOINT: "lavalink:2333"
      LAVALINK_PASSWORD: "youshallnotpass"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - lavalink

  lavalink:
    image: fredboat/lavalink:master-vv3.3.2.5
    volumes:
      - ./config/lavalink.yml:/opt/Lavalink/application.yml
  